import { contextBridge, ipcRenderer } from 'electron';
import type {
  CreateGithubSkillInput,
  CreateModuleInput,
  GiteeBatchTagInput,
  GiteeCredentialsInput,
  GiteeRepoMetaInput,
  GiteeRepositorySearchInput,
  GiteeStarRepositoryInput,
  GiteeStarSyncInput,
  GithubRepositorySearchInput,
  GithubStarCredentialsInput,
  GithubStarMetaInput,
  GithubStarRepositoryInput,
  GithubStarSyncInput,
  MarketplaceAddInput,
  MarketplaceInstallInput,
  LocalPromptScanOptions,
  PackageSkillsInput,
  SaveReusableSceneInput,
  SkillDirectory,
  SkillUsageEvent,
  SkillsManagerApi,
  SyncMode,
  UpdateAppSettingsInput
} from '../src/shared/types.js';

const api: SkillsManagerApi = {
  getStorageSettings: () => ipcRenderer.invoke('storage:get'),
  chooseStorageDirectory: () => ipcRenderer.invoke('storage:choose'),
  openStorageDirectory: () => ipcRenderer.invoke('storage:open'),
  switchStorageDirectory: (input) => ipcRenderer.invoke('storage:switch', input),
  loadPreferences: (legacy) => ipcRenderer.invoke('storage:preferences', legacy),
  savePreference: (key, value) => ipcRenderer.invoke('storage:preferenceSave', key, value),
  ping: () => ipcRenderer.invoke('app:ping') as Promise<string>,
  executeRtk: (action, client) => ipcRenderer.invoke('rtk:execute', action, client),
  exportTokenSavingGuide: () => ipcRenderer.invoke('prompts:exportGuide'),
  getTokenSavingFeatureStatus: (paths) => ipcRenderer.invoke('prompts:featureStatus', paths),
  setTokenSavingFeature: (paths, id, enabled, mode) => ipcRenderer.invoke('prompts:featureSet', paths, id, enabled, mode),
  copyText: (text: string) => ipcRenderer.invoke('clipboard:writeText', text),
  openExternalUrl: (url: string) => ipcRenderer.invoke('shell:openExternal', url),
  getAppSettings: () => ipcRenderer.invoke('settings:get'),
  saveAppSettings: (input: UpdateAppSettingsInput) => ipcRenderer.invoke('settings:save', input),
  getDirectories: () => ipcRenderer.invoke('directories:list'),
  saveDefaultDirectories: (directories: SkillDirectory[]) => ipcRenderer.invoke('directories:saveDefault', directories),
  saveCustomDirectories: (directories: SkillDirectory[]) => ipcRenderer.invoke('directories:saveCustom', directories),
  getDefaultModuleCandidates: () => ipcRenderer.invoke('modules:defaultCandidates'),
  createModule: (input: CreateModuleInput) => ipcRenderer.invoke('modules:create', input),
  removeModule: (directoryId: string) => ipcRenderer.invoke('modules:remove', directoryId),
  scanSkills: () => ipcRenderer.invoke('skills:scan'),
  scanLocalPrompts: (scanOptions?: LocalPromptScanOptions) => ipcRenderer.invoke('prompts:scan', scanOptions),
  readLocalPrompt: (promptPath: string) => ipcRenderer.invoke('prompts:read', promptPath),
  applyTokenSavingPrompt: (promptPaths: string[]) => ipcRenderer.invoke('prompts:tokenSavingApply', promptPaths),
  restoreTokenSavingPrompt: (promptPaths: string[]) => ipcRenderer.invoke('prompts:tokenSavingRestore', promptPaths),
  getTokenUsage: (days?: number) => ipcRenderer.invoke('tokenUsage:get', days),
  revealLocalPrompt: (promptPath: string) => ipcRenderer.invoke('prompts:reveal', promptPath),
  scanLocalClis: () => ipcRenderer.invoke('localTools:scanClis'),
  scanLocalMcps: () => ipcRenderer.invoke('localTools:scanMcps'),
  readLocalConfig: (configPath: string) => ipcRenderer.invoke('localTools:readConfig', configPath),
  revealLocalResource: (resourcePath: string) => ipcRenderer.invoke('localTools:reveal', resourcePath),
  scanLocalMemories: () => ipcRenderer.invoke('localAssets:scanMemories'),
  scanLocalPlugins: () => ipcRenderer.invoke('localAssets:scanPlugins'),
  scanLocalAgents: () => ipcRenderer.invoke('localAssets:scanAgents'),
  readLocalAsset: (assetPath: string) => ipcRenderer.invoke('localAssets:read', assetPath),
  revealLocalAsset: (assetPath: string) => ipcRenderer.invoke('localAssets:reveal', assetPath),
  scanLocalRepositories: (rootPath?: string) => ipcRenderer.invoke('localGit:scan', rootPath),
  chooseLocalRepositoryRoot: () => ipcRenderer.invoke('localGit:chooseRoot'),
  revealLocalRepository: (repositoryPath: string) => ipcRenderer.invoke('localGit:reveal', repositoryPath),
  listReusableScenes: () => ipcRenderer.invoke('scenes:list'),
  saveReusableScene: (input: SaveReusableSceneInput) => ipcRenderer.invoke('scenes:save', input),
  deleteReusableScene: (sceneId: string) => ipcRenderer.invoke('scenes:delete', sceneId),
  revealReusableSceneStore: () => ipcRenderer.invoke('scenes:revealStore'),
  readSkill: (skillPath: string) => ipcRenderer.invoke('skills:read', skillPath),
  setSkillEnabled: (skillPath: string, enabled: boolean) => ipcRenderer.invoke('skills:setEnabled', skillPath, enabled),
  setSkillCallTracking: (skillPath: string, skillId: string, enabled: boolean) =>
    ipcRenderer.invoke('skills:setCallTracking', skillPath, skillId, enabled),
  recordSkillCall: (skillPath: string, source?: SkillUsageEvent['source']) =>
    ipcRenderer.invoke('skills:recordCall', skillPath, source),
  openFolder: (folderPath: string) => ipcRenderer.invoke('skills:openFolder', folderPath),
  uninstallSkill: (skillPath: string) => ipcRenderer.invoke('skills:uninstall', skillPath),
  importLocalSkill: (sourcePath: string, targetDirectoryId?: string) =>
    ipcRenderer.invoke('skills:importLocal', sourcePath, targetDirectoryId),
  importGithubSkill: (repoUrl: string, targetDirectoryId?: string) =>
    ipcRenderer.invoke('skills:importGithub', repoUrl, targetDirectoryId),
  syncSkillToDirectory: (skillPath: string, targetDirectoryId: string, mode: SyncMode) =>
    ipcRenderer.invoke('skills:syncToDirectory', skillPath, targetDirectoryId, mode),
  syncRepositoryModule: (directoryId: string) => ipcRenderer.invoke('modules:syncRepository', directoryId),
  createGithubSkill: (input: CreateGithubSkillInput) => ipcRenderer.invoke('skills:createGithubSkill', input),
  checkGithubSkillUpdates: () => ipcRenderer.invoke('skills:checkGithubUpdates'),
  updateGithubSkill: (skillPath: string, skillId: string) =>
    ipcRenderer.invoke('skills:updateGithubSkill', skillPath, skillId),
  listMarketplaceSkills: () => ipcRenderer.invoke('marketplace:list'),
  addMarketplaceSkill: (input: MarketplaceAddInput) => ipcRenderer.invoke('marketplace:add', input),
  removeMarketplaceSkill: (id: string) => ipcRenderer.invoke('marketplace:remove', id),
  installMarketplaceSkill: (input: MarketplaceInstallInput) => ipcRenderer.invoke('marketplace:install', input),
  shareMarketplaceSkill: (id: string) => ipcRenderer.invoke('marketplace:share', id),
  getOperationLogs: () => ipcRenderer.invoke('logs:list'),
  getGithubStarSettings: () => ipcRenderer.invoke('githubStars:settings'),
  saveGithubStarCredentials: (input: GithubStarCredentialsInput) =>
    ipcRenderer.invoke('githubStars:saveCredentials', input),
  syncGithubStars: (input?: GithubStarSyncInput) => ipcRenderer.invoke('githubStars:sync', input),
  listGithubStars: () => ipcRenderer.invoke('githubStars:list'),
  updateGithubStarMeta: (input: GithubStarMetaInput) => ipcRenderer.invoke('githubStars:updateMeta', input),
  searchGithubRepositories: (input?: GithubRepositorySearchInput) =>
    ipcRenderer.invoke('githubStars:searchRepositories', input),
  starGithubRepository: (input: GithubStarRepositoryInput) => ipcRenderer.invoke('githubStars:starRepository', input),
  getGiteeSettings: () => ipcRenderer.invoke('gitee:settings'),
  saveGiteeCredentials: (input: GiteeCredentialsInput) => ipcRenderer.invoke('gitee:saveCredentials', input),
  syncGiteeStars: (input?: GiteeStarSyncInput) => ipcRenderer.invoke('gitee:sync', input),
  listGiteeStars: () => ipcRenderer.invoke('gitee:list'),
  updateGiteeRepoMeta: (input: GiteeRepoMetaInput) => ipcRenderer.invoke('gitee:updateMeta', input),
  tagGiteeRepositoriesByPrefix: (input: GiteeBatchTagInput) => ipcRenderer.invoke('gitee:tagByPrefix', input),
  searchGiteeRepositories: (input?: GiteeRepositorySearchInput) => ipcRenderer.invoke('gitee:searchRepositories', input),
  starGiteeRepository: (input: GiteeStarRepositoryInput) => ipcRenderer.invoke('gitee:starRepository', input),
  saveGiteeRepository: (input: { fullName: string }) => ipcRenderer.invoke('gitee:saveRepository', input),
  packageSkills: (input: PackageSkillsInput) => ipcRenderer.invoke('skills:package', input),
  optimizeSkill: (skillPath: string, skillId: string) => ipcRenderer.invoke('skills:optimize', skillPath, skillId),
  setSkillOptimization: (skillPath: string, skillId: string, enabled: boolean) =>
    ipcRenderer.invoke('skills:setOptimization', skillPath, skillId, enabled),
  recordSkillEvolution: (skillPath: string, skillId: string, note: string) =>
    ipcRenderer.invoke('skills:recordEvolution', skillPath, skillId, note),
  updateSkillUserMeta: (skillId: string, input: { favorite?: boolean; tags?: string[] }) =>
    ipcRenderer.invoke('skills:updateMeta', skillId, input),
  recordUsage: (
    skillId: string,
    eventType?: SkillUsageEvent['eventType'],
    source?: SkillUsageEvent['source'],
    note?: string
  ) => ipcRenderer.invoke('skills:recordUsage', skillId, eventType, source, note),
  scanSkillSecurity: (skillPath: string, skillId: string) => ipcRenderer.invoke('security:scanSkill', skillPath, skillId),
  scanAllSecurity: () => ipcRenderer.invoke('security:scanAll')
};

contextBridge.exposeInMainWorld('skillsManager', api);
